Develop/alex
bcgov/EDUC-GRAD-GRADUATION-API pull request #444
Opened 2023-05-08 16:05 UTC by arybakov-cgi

2023-07-17 15:41 UTC, cditcher requested changes

2023-07-17 16:29 UTC, arybakov-cgi commented on api/src/main/java/ca/bc/gov/educ/api/graduation/model/report/Transcript.java
> -    @JsonFormat(pattern="yyyy-MM-dd")
All done

2023-07-17 21:50 UTC, cditcher approved these changes

2023-07-21 17:17 UTC, cditcher approved these changes

2023-07-21 20:31 UTC, merged